package exception_handling.try_catch;

//Main programfor ExceptionDemo

public class Exceptionmain {
	public static void main(String[] args) {
		Exceptiondemo.divide(12, 3);
		Exceptiondemo.divide(12, 0);
	}
}
